-- Alignement schéma Prisma ↔ DB neuve (colonnes absentes de init historique)
-- Idempotent : safe si déjà partiellement appliqué

-- ── Eglise ───────────────────────────────────────────────────
ALTER TABLE "Eglise" ADD COLUMN IF NOT EXISTS "lienFacebook" TEXT;
ALTER TABLE "Eglise" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Eglise" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ── Cellule ──────────────────────────────────────────────────
ALTER TABLE "Cellule" ADD COLUMN IF NOT EXISTS "reference" TEXT;
ALTER TABLE "Cellule" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Cellule" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ── Departement ──────────────────────────────────────────────
ALTER TABLE "Departement" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Departement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ── Evenement : date → dateDebut si besoin ───────────────────
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Evenement' AND column_name = 'date'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Evenement' AND column_name = 'dateDebut'
  ) THEN
    ALTER TABLE "Evenement" RENAME COLUMN "date" TO "dateDebut";
  END IF;
END $$;

ALTER TABLE "Evenement" ADD COLUMN IF NOT EXISTS "dateDebut" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Evenement" ADD COLUMN IF NOT EXISTS "dateFin" TIMESTAMP(3);
ALTER TABLE "Evenement" ADD COLUMN IF NOT EXISTS "imageExterneUrl" TEXT;
ALTER TABLE "Evenement" ADD COLUMN IF NOT EXISTS "organisateur" TEXT;
ALTER TABLE "Evenement" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Evenement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

DROP INDEX IF EXISTS "Evenement_date_idx";
CREATE INDEX IF NOT EXISTS "Evenement_dateDebut_idx" ON "Evenement"("dateDebut");

-- ── Emission ─────────────────────────────────────────────────
ALTER TABLE "Emission" ADD COLUMN IF NOT EXISTS "mediaUrl" TEXT;
ALTER TABLE "Emission" ADD COLUMN IF NOT EXISTS "cloudinaryPublicId" TEXT;
ALTER TABLE "Emission" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Emission" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Emission" ALTER COLUMN "lienYoutube" DROP NOT NULL;

-- ── Culte / FcmToken / Conversation ──────────────────────────
ALTER TABLE "Culte" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Culte" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "FcmToken" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "FcmToken" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ── RendezVous ───────────────────────────────────────────────
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "nomVisiteur" TEXT;
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "prenomVisiteur" TEXT;
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "whatsappVisiteur" TEXT;
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "RendezVous" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "RendezVous" ALTER COLUMN "userId" DROP NOT NULL;
-- motif peut déjà être NOT NULL ; si NULL présents, on met une valeur par défaut avant
UPDATE "RendezVous" SET "motif" = 'Non précisé' WHERE "motif" IS NULL;
ALTER TABLE "RendezVous" ALTER COLUMN "motif" SET NOT NULL;

-- ── Requete ──────────────────────────────────────────────────
ALTER TABLE "Requete" ADD COLUMN IF NOT EXISTS "reponseAdmin" TEXT;

-- ── Playlist / Sermon / Short / Citation / Verset timestamps ─
ALTER TABLE "PlaylistSermon" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PlaylistSermon" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Sermon" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Sermon" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ShortVideo" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ShortVideo" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Citation" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Citation" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "VersetJour" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "VersetJour" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Requete" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Requete" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
