"""
Configuration de l'intégration et des paramètres WhatsApp de l'application (singleton).
"""
type ConfigurationWhatsApp {
  lienGroupeWhatsapp: String
  numeroWhatsappBookshop: String
}

extend type Query {
  """
  Retourne la configuration WhatsApp paramétrée de l'application. Accessible publiquement.
  """
  getConfigurationWhatsApp: ConfigurationWhatsApp!
}

extend type Mutation {
  """
  Met à jour la configuration WhatsApp de l'application. Réservé au SUPER_ADMIN.
  """
  modifierConfigurationWhatsApp(
    lienGroupeWhatsapp: String
    numeroWhatsappBookshop: String
  ): ConfigurationWhatsApp!
}
